preserve_hierarchy: true
commit_message: "(automated) Translations from Crowdin"
append_commit_message: false

files:
- source: /json/**/en.json
  translation: /json-translated/**/%locale%.json
  skip_untranslated_files: true
  skip_untranslated_strings: true
